### PR TITLE
TwitRSS.me in a docker container

### PR DESCRIPTION
**Pull request by sdt**
First let me say thanks very much for creating TwitRSS.me - I've been using it in conjunction with [rss2imap](https://github.com/rcarmo/rss2imap) for quite a while now.

I saw you were having rate limiting issues, and suggesting people run their own instances.

Here's a Dockerfile and a few other bits and pieces which will hopefully make that easier for people to do.

I've created an [automated build](https://hub.docker.com/r/sdthirlwall/twitrssme/) on docker hub as a sample. You can try it out with:

  `docker run --rm -p 3000:80 sdthirlwall/twitrssme`

That will pull the image and run up a local TwitRSS.me server on http://localhost:3000/

There's a bit more information in INSTALL.docker.md

### CODE REVIEW

**Comment by sdt** [comment]
I also added a cpanfile which simplifies installing CPAN modules.

 `cpanm --installdeps .`

**Comment by ciderpunx** [comment]
That's awesome! Many thanks :-)

**Comment by shakeyourbunny** [comment]
My personal docker instance produces the same instance as twitrssme:

http://192.168.1.111:3000/twitter_user_to_rss/?user=dosnostalgic

--> 

ERR: Can’t screenscrape Twitter

Redirecting you back to TwitRSS.me in a few seconds. You might have spelled the username wrong or something

**Comment by sdt** [comment]
@shakeyourbunny I wonder if Twitter is blocking/rate limiting your IP somehow?

Can you open https://twitter.com/dosnostalgic in your browser?

That feed seems to work for me.

**Comment by shakeyourbunny** [comment]
I don't have any problems opening the "normal" twitter page, but with the docker container, there seems to be no dice ;(

**Pull request merged**
